version: "3.8"

services:
    php:
        image: php:8.3-fpm
        volumes:
            - ./app:/var/www/html
        networks:
            - symfony

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            #repertoire de l'application sur le disque dur : app
            #repertoire de l'application dans le docker nginx : /var/www/html            
            - ./app:/var/www/html
            #repertoire du fichier de config sur le disque dur : /nginx/
            #repertoire du fichier dans le docker nginx : /etc/nginx/conf.d/
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - symfony

    db:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: secret
        networks:
            - symfony

networks:
    symfony:
    